language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  # Go back one step
  - cd ..

  # Clone base Distribution
  - git clone git://git.typo3.org/Flow/Distributions/Base.git Base
  - cd Base
  - git fetch origin
  - git checkout -b 