language: php

php:
  - 5.3
  - 5.4
  - 5.5
#   - hhvm

# matrix:
#   allow_failures:
#     - php: hhvm

before_script:
  # Go back one step
  - cd ..

  # Clone base Distribution
  - git clone git://git.typo3.org/Flow/Distributions/Base.git Base
  - cd Base
  - git fetch origin
  - git checkout -b "2.1" "origin/2.1"

  # Install Flow in different versions
  - composer install --prefer-source

  # remove package installed by composer and replace it with the travis checkout
  - rm -rf Packages/Framework/TYPO3.Flow
  - mv ../TYPO3.Flow Packages/Framework/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script:
    - phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml
    - phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml
    # - phpunit --coverage-clover=coverage.clover -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Famelo.Messaging/Tests/Functional
